name = "overtime-tracker-otp"
main = "src/index.js"
compatibility_date = "2026-08-01"

[[kv_namespaces]]
binding = "OTP_KV"
id = "4cd0462d18d148a38eba3b1df83b6a5e"

[[kv_namespaces]]
binding = "ADMIN_KV"
id = "f1be83902f924e709ef1e2a007f9cfbd"

[[kv_namespaces]]
binding = "RECORDS_KV"
id = "97fe1f86dfa64db5a9b70d9cff98e2d8"

# Secrets are NOT stored here.
# Set them with:
# npx wrangler secret put BREVO_API_KEY
# npx wrangler secret put SENDER_EMAIL
